name: action
on: [push]

#https://stackoverflow.com/questions/75460950/github-actions-run-jobs-in-webserver-container-unable-to-connect-to-localhost
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/go-app:1.0.${{ github.run_number }}
  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      json:
        image: ${{ vars.DOCKERHUB_USERNAME }}/go-app:1.0.${{ github.run_number }}
        ports:
        - 80:80
    steps:
      - name: Run Tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          project_id: liatrio-demo-475423
          workload_identity_provider: projects/892806361271/locations/global/workloadIdentityPools/github/providers/liatrio-interview-exercise
      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v3
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy
        run: |-
          ./kustomize edit set image ${{ vars.DOCKERHUB_USERNAME }}/go-app=${{ vars.DOCKERHUB_USERNAME }}/go-app:1.0.${{ github.run_number }}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
