name: action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      json:
        image: ${{ vars.DOCKERHUB_USERNAME }}/go-app:1.0.9 # hardcoded for testing
        ports:
        - 80:80
    steps:
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

#https://stackoverflow.com/questions/75460950/github-actions-run-jobs-in-webserver-container-unable-to-connect-to-localhost
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: ${{ vars.DOCKERHUB_USERNAME }}/go-app:1.0.${{ github.run_number }}
#      - name: Start Container
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ vars.DOCKERHUB_USERNAME }}/go-app:1.0.${{ github.run_number }}
#          options: -d -p 80:80
#      - name: Run Tests
#        uses: liatrio/github-actions/apprentice-action@master
